# Changes here will be overwritten by Copier
AddAllcontributors: true
AddCodeOfConduct: true
AddContributionDocs: false
AddCopierCI: false
AddGitHubTemplates: true
AddMacToCI: false
AddPrecommit: true
AddWinToCI: false
AnswerStrategy: ask
Authors: Benedikt Ehinger <benedikt.ehinger@vis.uni-stuttgart.de>
AutoIncludeTests: false
CheckExplicitImports: false
CodeOfConductContact: benedikt.ehinger@vis.uni-stuttgart.de
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Benedikt Ehinger
MarkdownIndentation: 2
PackageName: UnfoldMixedModels
PackageOwner: unfoldtoolbox
PackageUUID: 019ae9e0-8363-565c-86e5-97a5a2fe84f4
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
